package cnit425semesterproject.pixelpi;

import android.content.Context;
import android.content.res.Resources;
import android.graphics.Color;
import android.support.v4.content.res.TypedArrayUtils;

import org.json.JSONException;
import org.json.JSONObject;

/**
 * Created by jackb on 4/15/2018.
 */

//Supertype of tasks that devices
public class DeviceTask implements JSON {
    protected String mode; //type of devicetask
    protected String name;
    protected int id; //generated by database
    protected boolean activated;
    protected Context context;

    //getter and setters
    public String getMode() {
        return mode;
    }

    public void setMode(String mode) {
        this.mode = mode;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public boolean isActivated() {
        return activated;
    }

    public void setActivated(boolean activated) {
        this.activated = activated;
    }

    public Context getContext() {
        return context;
    }

    public void setContext(Context context) {
        this.context = context;
    }

    //other methods

    //interfaces
    @Override
    public JSONObject toJSON()
    {
        JSONObject jsonObject = new JSONObject();
        try {
            jsonObject.put("mode", this.mode);
            jsonObject.put("name", this.name);
            jsonObject.put("task id", this.id);
        } catch (JSONException e) {
            e.printStackTrace();
        }
        return jsonObject;
    }


    //constructors
    public DeviceTask(String mode, String name, int id, boolean activated, Context context) {
        this.mode = mode;
        this.name = name;
        this.id = id;
        this.activated = activated;
        this.context = context;
    }

    //new task
    public DeviceTask(String name, Context context)
    {
        this.id = -1;
        this.activated = false;
        this.name = name;
        this.context = context;
        this.mode = context.getString(R.string.NO_MODE); //error

    }

    public DeviceTask(JSONObject jsonObject)  //build devicetask from json
    {
        String mode = "";
        String name = "";
        int id;
        try {
            mode = jsonObject.getString("mode");
            name = jsonObject.getString("name");
            id = jsonObject.getInt("id");
            this.mode = mode;
            this.name = name;
            this.id = id;
            this.activated = false;
        } catch (JSONException e) {
            e.printStackTrace();
        }
    }

}
